version: 2
jobs:
  validate-code:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Validate Vault
          command: terraform validate -check-variables=false ./azure/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate-code