version: 2
jobs:
  validate-code:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Validate Terraform
          command: terraform validate -check-variables=false ./azure/
  run-functional-tests-inspec:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec Tests
          no_output_timeout: 30m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec -b winrm --show-progress --host uat-tf-vault.centralus.cloudapp.azure.com --user hashicorp --password $WORKSTATION_PASSWORD --reporter cli junit:test_results/inspec/results.xml -- azure/test/inspec/os azure/test/inspec/training
      - store_test_results:
          path: test_results
  clean-up-uat:
    docker:
      - image: microsoft/azure-cli:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Clean up UAT environment
          no_output_timeout: 30m
          command: |
            # Delete the UAT environment
            az login --service-principal -u http://SE-Training-Workstation-Creds -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID;
            az group delete -y --name uat-tf-vault-lab-workshop;
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate-code
      - run-functional-tests-inspec:
          requires:
            - validate-code
      - clean-up-uat:
          requires:
            - run-functional-tests-inspec
  nightly-build:
    triggers:
      - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only:
              - master
    jobs:
      - validate-code
      - run-functional-tests-inspec:
          requires:
            - validate-code
      - clean-up-uat:
          requires:
            - run-functional-tests-inspec